name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name:  'Publish Version'
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: echo {{ version }}
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SNPM_TOKEN }}
