name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: 'Setup Git'
        run: |
          git config --global user.email "andreasonny83@gmail.com"
          git config --global user.name ${{ github.event.release.author.login }}

      - name: 'Bump Version'
        run: npm version ${{ github.event.release.tag_name }}

      - name: 'Install'
        run: yarn

      - name: 'Publish'
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Commit version change'
        run: git push origin ${{ github.event.repository.default_branch }} -f
